name: plateitup
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  badges: ^3.1.2
  cached_network_image: ^3.4.0
  cloud_firestore: ^4.15.8
  cloud_firestore_platform_interface: ^6.1.9
  cloud_firestore_web: ^3.10.8
  collection: 1.18.0
  dropdown_button2: 2.3.9
  easy_debounce: ^2.0.3
  expandable: 5.0.1
  file_picker: ^8.0.0+1
  firebase_auth: ^4.17.8
  firebase_auth_platform_interface: ^7.1.8
  firebase_auth_web: ^5.9.8
  firebase_core: ^2.27.0
  firebase_core_platform_interface: ^5.3.0
  firebase_core_web: 2.11.5
  firebase_performance: ^0.9.3+17
  firebase_performance_platform_interface: ^0.1.4+25
  firebase_performance_web: ^0.1.4+25
  firebase_storage: ^11.6.9
  firebase_storage_platform_interface: ^5.1.12
  firebase_storage_web: ^3.7.3
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.4.1
  flutter_local_notifications: ^18.0.1
  flutter_plugin_android_lifecycle: ^2.0.23
  flutter_rating_bar: 4.0.1
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  go_router: ^14.6.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  google_sign_in_android: ^6.1.33
  google_sign_in_ios: ^5.7.8
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.3+3
  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+17
  image_picker_for_web: ^3.0.2
  image_picker_ios: ^0.8.12+1
  image_picker_platform_interface: ^2.10.0
  intl: 0.19.0
  json_path: ^0.7.4
  mime_type: ^1.0.1
  page_transition: 2.1.0
  path_provider: ^2.1.5
  path_provider_android: ^2.2.12
  path_provider_foundation: ^2.4.0
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: 2.1.8
  provider: ^6.1.2
  rxdart: ^0.28.0
  shared_preferences: ^2.2.3
  shared_preferences_android: ^2.3.3
  shared_preferences_foundation: ^2.5.3
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: ^2.2.2
  sign_in_with_apple: ^6.1.3
  sign_in_with_apple_platform_interface: ^1.1.0
  sign_in_with_apple_web: ^2.1.0
  sqflite: ^2.4.1
  stream_transform: 2.1.0
  text_search: ^1.0.2
  time_picker_spinner: ^1.0.0
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.14
  url_launcher_ios: ^6.3.1
  url_launcher_platform_interface: 2.3.2
  video_player: ^2.9.2
  video_player_android: ^2.7.16
  video_player_avfoundation: ^2.6.2
  video_player_platform_interface: ^6.2.3
  video_player_web: ^2.2.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  image: ^4.3.0
  lints: ^5.0.0

  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

